version: '3'

vars:
  VENV_DIR: .venv
  PYTHON_BIN: "{{.VENV_DIR}}/bin"
  UV: "{{.PYTHON_BIN}}/uv"
  PIP: "{{.PYTHON_BIN}}/pip"
  RUFF: "{{.PYTHON_BIN}}/ruff"
  SOURCE_DIRS: "."

tasks:
  venv:init:
    desc: "Initialize virtual environment and install uv"
    cmds:
      - python -m venv "{{.VENV_DIR}}" --upgrade-deps
      - "{{.PIP}} install uv"
      - "{{.UV}} sync"
    status:
      - test -f "{{.UV}}"

  venv:install:
    desc: "Install project dependencies in editable mode"
    cmds:
      - "{{.UV}} pip install -e . --group dev"
    sources:
      - pyproject.toml
    generates:
      - "{{.VENV_DIR}}/lib/python*/site-packages/*"

  venv:sync:
    desc: "Sync venv with lockfile (uv.lock)"
    cmds:
      - "{{.UV}} sync --group dev"

  venv:add:
    desc: "Add one or more packages to dependencies"
    cmds:
      - "{{.UV}} add {{.CLI_ARGS}}"

  venv:add:dev:
    desc: "Add one or more packages to dev dependencies"
    cmds:
      - "{{.UV}} add --dev {{.CLI_ARGS}}"

  venv:outdated:
    desc: "Check for outdated dependencies"
    cmds:
      - "{{.UV}} pip list --outdated"

  venv:upgrade:
    desc: "Upgrade dependencies to latest versions"
    cmds:
      - "{{.UV}} lock --upgrade"
      - "{{.UV}} sync --group dev"

  venv:upgrade:tools:
    desc: "Upgrade pip and uv to latest versions"
    cmds:
      - "{{.PIP}} install --upgrade pip uv"

  code:lint:
    desc: "Run linting checks (ruff check)"
    cmds:
      - "{{.RUFF}} check {{.SOURCE_DIRS}}"

  code:lint:fix:
    desc: "Run linting and auto-fix issues"
    cmds:
      - "{{.RUFF}} check --fix {{.SOURCE_DIRS}}"

  code:format:
    desc: "Format code with ruff"
    cmds:
      - "{{.RUFF}} format {{.SOURCE_DIRS}}"

  code:format:check:
    desc: "Check if code is formatted (no changes)"
    cmds:
      - "{{.RUFF}} format --check {{.SOURCE_DIRS}}"

  code:check:
    desc: "Run all checks (lint + format check) - use in CI"
    cmds:
      - task: code:lint
      - task: code:format:check

  code:fix:
    desc: "Auto-fix all issues (lint + format)"
    cmds:
      - task: code:lint:fix
      - task: code:format

  code:clean:
    desc: "Clean cache files"
    cmds:
      - rm -rf .ruff_cache
      - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete

  code:show:config:
    desc: "Show ruff configuration"
    cmds:
      - "{{.RUFF}} check --show-settings {{.SOURCE_DIRS}}"
