version: "3"

vars:
  VENV_DIR: .venv
  PYTHON_BIN: "{{.VENV_DIR}}/bin"
  UV: "{{.PYTHON_BIN}}/uv"
  PIP: "{{.PYTHON_BIN}}/pip"
  RUFF: "{{.PYTHON_BIN}}/ruff"
  VALIDATE_PYPROJECT: "{{.PYTHON_BIN}}/validate-pyproject"
  LIGHTNING: "{{.PYTHON_BIN}}/lightning"
  SOURCE_DIRS: "."
  # Lightning Studio configuration
  LIGHTNING_STUDIO_NAME: alyra-dl
  LIGHTNING_TEAMSPACE: stephanewirtel/tool-exploration-project
  LIGHTNING_TEAMSPACE_SHORT: tool-exploration-project
  LIGHTNING_STUDIO_URI: "lit://stephanewirtel/tool-exploration-project/studios/alyra-dl"

tasks:
  venv:init:
    desc: "Initialize virtual environment and install uv"
    cmds:
      - python -m venv "{{.VENV_DIR}}" --upgrade-deps
      - "{{.PIP}} install uv"
      - "{{.UV}} sync"
    status:
      - test -f "{{.UV}}"

  venv:install:
    desc: "Install project dependencies in editable mode"
    deps: [venv:init]
    cmds:
      - "{{.UV}} pip install -e . --group dev"
    sources:
      - pyproject.toml
    generates:
      - "{{.VENV_DIR}}/lib/python*/site-packages/*"

  venv:sync:
    desc: "Sync venv with lockfile (uv.lock)"
    deps: [venv:init]
    cmds:
      - "{{.UV}} sync --group dev"

  venv:add:
    desc: "Add one or more packages to dependencies"
    deps: [venv:init]
    cmds:
      - "{{.UV}} add {{.CLI_ARGS}}"

  venv:add:dev:
    desc: "Add one or more packages to dev dependencies"
    deps: [venv:init]
    cmds:
      - "{{.UV}} add --dev {{.CLI_ARGS}}"

  venv:outdated:
    desc: "Check for outdated dependencies"
    deps: [venv:init]
    cmds:
      - "{{.UV}} pip list --outdated"

  venv:upgrade:
    desc: "Upgrade dependencies to latest versions"
    deps: [venv:init]
    cmds:
      - "{{.UV}} lock --upgrade"
      - "{{.UV}} sync --group dev"

  venv:upgrade:tools:
    desc: "Upgrade pip and uv to latest versions"
    deps: [venv:init]
    cmds:
      - "{{.PIP}} install --upgrade pip uv"

  code:lint:
    desc: "Run linting checks (ruff check)"
    deps: [venv:init]
    cmds:
      - "{{.RUFF}} check {{.SOURCE_DIRS}}"

  code:lint:fix:
    desc: "Run linting and auto-fix issues"
    deps: [venv:init]
    cmds:
      - "{{.RUFF}} check --fix {{.SOURCE_DIRS}}"

  code:format:
    desc: "Format code with ruff"
    deps: [venv:init]
    cmds:
      - "{{.RUFF}} format {{.SOURCE_DIRS}}"

  code:format:check:
    desc: "Check if code is formatted (no changes)"
    deps: [venv:init]
    cmds:
      - "{{.RUFF}} format --check {{.SOURCE_DIRS}}"

  code:check:
    desc: "Run all checks (lint + format check) - use in CI"
    cmds:
      - task: code:lint
      - task: code:format:check
      - task: code:validate:pyproject

  code:fix:
    desc: "Auto-fix all issues (lint + format)"
    cmds:
      - task: code:lint:fix
      - task: code:format

  code:clean:
    desc: "Clean cache files"
    cmds:
      - rm -rf .ruff_cache
      - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete

  code:show:config:
    desc: "Show ruff configuration"
    deps: [venv:init]
    cmds:
      - "{{.RUFF}} check --show-settings {{.SOURCE_DIRS}}"

  code:validate:pyproject:
    desc: "Validate pyproject.toml against PEP standards"
    deps: [venv:init]
    cmds:
      - "{{.VALIDATE_PYPROJECT}} pyproject.toml"

  lightning:login:
    desc: "Login to Lightning AI"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} login"

  lightning:logout:
    desc: "Logout from Lightning AI"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} logout"

  lightning:studio:list:
    desc: "List Lightning AI studios"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio list"

  lightning:studio:list:all:
    desc: "List all Lightning AI studios (not just yours)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio list --all"

  lightning:studio:start:
    desc: "Start the default Lightning studio (alyra-dl)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio start --name {{.LIGHTNING_STUDIO_NAME}} --teamspace {{.LIGHTNING_TEAMSPACE}}"

  lightning:studio:start:t4:
    desc: "Start the Lightning studio with T4 GPU"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio start --name {{.LIGHTNING_STUDIO_NAME}} --teamspace {{.LIGHTNING_TEAMSPACE}} --machine T4"

  lightning:studio:start:custom:
    desc: "Start a specific Lightning studio (use -- --name <name>)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio start --teamspace {{.LIGHTNING_TEAMSPACE}} {{.CLI_ARGS}}"

  lightning:studio:switch:t4:
    desc: "Switch the default Lightning studio to T4 machine"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio switch --name {{.LIGHTNING_STUDIO_NAME}} --machine T4"

  lightning:studio:stop:
    desc: "Stop the default Lightning studio (alyra-dl)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio stop --name {{.LIGHTNING_STUDIO_NAME}} --teamspace {{.LIGHTNING_TEAMSPACE}}"

  lightning:studio:stop:custom:
    desc: "Stop a specific Lightning studio (use -- --name <name>)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio stop --teamspace {{.LIGHTNING_TEAMSPACE}} {{.CLI_ARGS}}"

  lightning:studio:ssh:
    desc: "SSH into the default Lightning studio (alyra-dl)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio ssh --teamspace {{.LIGHTNING_TEAMSPACE}} --name {{.LIGHTNING_STUDIO_NAME}}"

  lightning:studio:ssh:custom:
    desc: "SSH into a specific Lightning studio (use -- --name <name>)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio ssh --teamspace {{.LIGHTNING_TEAMSPACE}} {{.CLI_ARGS}}"

  lightning:studio:delete:
    desc: "Delete the default Lightning studio (alyra-dl)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio delete --name {{.LIGHTNING_STUDIO_NAME}} --teamspace {{.LIGHTNING_TEAMSPACE}}"

  lightning:studio:delete:custom:
    desc: "Delete a specific Lightning studio (use -- --name <name>)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio delete --teamspace {{.LIGHTNING_TEAMSPACE}} {{.CLI_ARGS}}"

  lightning:studio:cp:
    desc: "Copy files to/from Lightning studio (use -- <source> <dest>)"
    deps: [venv:init]
    cmds:
      - "{{.LIGHTNING}} studio cp {{.CLI_ARGS}}"

  lightning:studio:download:model:
    desc: "Download model from Lightning studio"
    deps: [venv:init]
    vars:
      MODEL_NAME: '{{.CLI_ARGS | default "symptom_classifier"}}'
    cmds:
      - mkdir -p models/{{.MODEL_NAME}}
      - "{{.LIGHTNING}} download folder --studio {{.LIGHTNING_TEAMSPACE_SHORT}}/{{.LIGHTNING_STUDIO_NAME}} --local-path models/{{.MODEL_NAME}} models/{{.MODEL_NAME}}/final"

  lightning:studio:download:results:
    desc: "Download all training results (models + logs)"
    deps: [venv:init]
    cmds:
      - mkdir -p models logs
      - "{{.LIGHTNING}} studio cp {{.LIGHTNING_STUDIO_URI}}/models/ ./models/"
      - "{{.LIGHTNING}} studio cp {{.LIGHTNING_STUDIO_URI}}/logs/ ./logs/"

  ml:tensorboard:
    desc: "Launch TensorBoard to visualize training logs"
    deps: [venv:init]
    cmds:
      - echo "Starting TensorBoard at http://localhost:6006"
      - echo "Press Ctrl+C to stop"
      - "{{.PYTHON_BIN}}/tensorboard --logdir models --port 6006"

  ml:tensorboard:custom:
    desc: "Launch TensorBoard for specific model directory"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/tensorboard {{.CLI_ARGS}}"

  ml:analyze:
    desc: "Analyze training logs and generate plots"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/python analyze_training_logs.py {{.CLI_ARGS}}"

  ml:analyze:compare:
    desc: "Compare multiple training runs"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/python analyze_training_logs.py --compare {{.CLI_ARGS}}"

  ml:train:standard:
    desc: "Train standard model on all 6 diseases"
    deps: [venv:init]
    vars:
      DISEASES: "anxiety,cystitis,herniated disk,panic disorder,pneumonia,spondylolisthesis"
      OUTPUT_DIR: "models/symptom_classifier"
    cmds:
      - "{{.PYTHON_BIN}}/python scripts/training/train_model.py '{{.DISEASES}}' --data-path data/prepared-dataset.csv --output-dir {{.OUTPUT_DIR}} {{.CLI_ARGS}}"

  ml:train:recall:
    desc: "Train model optimized for recall (medical contexts)"
    deps: [venv:init]
    vars:
      DISEASES: "anxiety,cystitis,herniated disk,panic disorder,pneumonia,spondylolisthesis"
      OUTPUT_DIR: "models/symptom_classifier_recall"
    cmds:
      - "{{.PYTHON_BIN}}/python scripts/training/train_model_recall.py '{{.DISEASES}}' --data-path data/prepared-dataset.csv --output-dir {{.OUTPUT_DIR}} {{.CLI_ARGS}}"

  ml:train:quick:
    desc: "Quick training test with 2 diseases only (for development)"
    deps: [venv:init]
    vars:
      DISEASES: "anxiety,pneumonia"
      OUTPUT_DIR: "models/symptom_classifier_quick"
    cmds:
      - "{{.PYTHON_BIN}}/python scripts/training/train_model.py '{{.DISEASES}}' --data-path data/prepared-dataset.csv --output-dir {{.OUTPUT_DIR}} --epochs 20 {{.CLI_ARGS}}"

  ml:prepare:dataset:
    desc: "Prepare dataset from augmented source for training"
    deps: [venv:init]
    vars:
      INPUT_FILE: "data/Final_Augmented_dataset_Diseases_and_Symptoms.csv"
      OUTPUT_FILE: "data/prepared-dataset.csv"
      DISEASES: "anxiety,cystitis,herniated disk,panic disorder,pneumonia,spondylolisthesis"
    cmds:
      - "{{.PYTHON_BIN}}/python scripts/data/prepare_dataset.py --input {{.INPUT_FILE}} --output {{.OUTPUT_FILE}} --diseases '{{.DISEASES}}' {{.CLI_ARGS}}"

  app:cli:
    desc: "Start CLI symptom analyzer"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/python -m alyra_ai_dl.apps.cli {{.CLI_ARGS}}"

  app:api:dev:
    desc: "Start FastAPI development server"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/python -m alyra_ai_dl.apps.api"

  app:streamlit:dev:
    desc: "Start Streamlit development server"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/streamlit run src/alyra_ai_dl/apps/streamlit_app.py"

  app:chainlit:dev:
    desc: "Start Chainlit chat interface"
    deps: [venv:init]
    cmds:
      - "{{.PYTHON_BIN}}/chainlit run src/alyra_ai_dl/apps/chainlit_app.py"

  demo:cli:record:
    desc: "Record CLI demo with asciinema"
    deps: [venv:init]
    vars:
      OUTPUT_FILE: '{{.CLI_ARGS | default "alyra-ai-dl-cli"}}'
    cmds:
      - asciinema rec {{.OUTPUT_FILE}} -c "task app:cli -- --llm --llm-backend=lightning"

  demo:cli:gif:
    desc: "Convert asciinema recording to GIF"
    vars:
      INPUT_FILE: '{{.CLI_ARGS | default "alyra-ai-dl-cli"}}'
    cmds:
      - agg {{.INPUT_FILE}} {{.INPUT_FILE}}.gif

  demo:cli:mp4:
    desc: "Convert GIF to MP4 with ffmpeg"
    vars:
      INPUT_FILE: '{{.CLI_ARGS | default "alyra-ai-dl-cli"}}'
    cmds:
      - ffmpeg -i {{.INPUT_FILE}}.gif {{.INPUT_FILE}}.mp4

  demo:cli:all:
    desc: "Record CLI demo and convert to GIF and MP4"
    vars:
      OUTPUT_FILE: '{{.CLI_ARGS | default "alyra-ai-dl-cli"}}'
    cmds:
      - task: demo:cli:record
        vars: { OUTPUT_FILE: "{{.OUTPUT_FILE}}" }
      - task: demo:cli:gif
        vars: { INPUT_FILE: "{{.OUTPUT_FILE}}" }
      - task: demo:cli:mp4
        vars: { INPUT_FILE: "{{.OUTPUT_FILE}}" }
